### ISSUE TITLE
Example List 404's

### ISSUE THREAD

**Issue by NDuma** [kurtfunai/Giftsmash#4]
![404 img](http://image.prntscr.com/image/3edb8ac5c3cd486d9395f2bfbceeb807.png)

https://github.com/kurtfunai/Giftsmash/blame/master/README.md#L13

ToDo:
[ ] Sign up
[ ] Make New List
[ ] Update Readme & PULL

**Comment by kurtfunai** [comment]
Thank you for the issue report 😃
